load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Ensure Python Rules Are Loaded
http_archive(
    name = "rules_python",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.29.0/rules_python-0.29.0.tar.gz"],
    strip_prefix = "rules_python-0.29.0",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

# Register System Python (Update the Path Accordingly)
python_register_toolchains(
    name = "python3",
    python_version = "3.10",  # Change this to match your Python version
    python_path = "/usr/bin/python3",  # Update this path using `which python3`
)
