load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load Python Rules
http_archive(
    name = "rules_python",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.29.0/rules_python-0.29.0.tar.gz"],
    strip_prefix = "rules_python-0.29.0",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

# Register Conda Python
python_register_toolchains(
    name = "python3",
    python_version = "3.10",  # Update if your Conda Python is a different version
    python_path = "/home/nipa/anaconda3/bin/python3",  # This should match `which python3`
)
