name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting with pylint and black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint black

      - name: Run black (Formatter Check)
        run: |
          if [ -d "src" ] || [ -d "tests" ]; then
            black --check src tests
          else
            echo "Warning: No Python source directories found. Skipping Black check."
            exit 0
          fi

      - name: Run pylint (Linter)
        run: |
          if [ -d "src" ] || [ -d "tests" ]; then
            pylint src/*.py tests/*.py --fail-under=8.0
          else
            echo "Warning: No Python source directories found. Skipping Pylint check."
            exit 0
          fi

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint  # Runs only if linting passes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pylint black

      - name: Run Unit Tests
        run: |
          if [ -d "tests" ]; then
            pytest tests/
          else
            echo "Warning: No test directory found. Skipping tests."
            exit 0
          fi
