name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Ensure Bazel Workspace Exists
        working-directory: project-root  # Ensure we run inside the correct directory
        run: |
          if [ ! -f WORKSPACE ] && [ ! -f MODULE.bazel ]; then
            echo "ERROR: Bazel workspace not found in python-bazel-ci!" >&2
            exit 1
          fi
        shell: bash

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        working-directory: project-root
        run: |
          pip install pylint black pytest

      - name: Run Unit Tests
        working-directory: project-root
        run: bazel test //tests:test_math_utils //tests:test_string_utils

      - name: Run Black Formatter Check
        working-directory: project-root
        run: black --check --exclude 'external|bazel-|third_party' .
        
      - name: Run Pylint
        working-directory: project-root
        run: pylint tests src  

      - name: Run Formatter Check
        working-directory: project-root
        run: bazel test //:format

      - name: Run Linter Check
        working-directory: project-root
        run: bazel test //:lint
